name: password_manager_back
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:

  collection: ^1.18.0
  drift: ^2.16.0
  path: ^1.9.0
  shelf: ^1.4.1
  get_it: ^7.6.7
  shelf_router: ^1.1.4
  shelf_router_generator: ^1.1.0
  dart_jsonwebtoken: ^2.13.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.4

  socket_io: ^1.0.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  drift_dev: ^2.16.0
  build_runner: ^2.4.8
